version: "3"

services:
  cv_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cv_app
      - cv_static_volume:/cv_app/static
      - cv_files_volume:/cv_app/files
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - cv_network
      - nginx_network
    depends_on:
      - cv_postgresql
  cv_postgresql:
    image: postgres:12
    container_name: coronavirus_postgresql
    volumes:
      - coronavirus_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - cv_network

volumes:
  coronavirus_postgresql:
    external: true
  cv_static_volume:
    external: true
  cv_files_volume:
    external: true
networks:
  cv_network:
    external: true
  nginx_network:
    external: true
