version: "3.8"

services:

  cv_postgresql:
    image: postgres:12
    container_name: coronavirus_postgresql
    volumes:
      - coronavirus_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - cv_network

volumes:
  coronavirus_postgresql:
    external: true
networks:
  cv_network:
    external: true
