# Generated by Django 3.0.4 on 2020-03-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=50)),
                ('countryKurdishName', models.CharField(default='', max_length=50)),
                ('_id', models.IntegerField(default=0)),
                ('ios2', models.CharField(default='', max_length=2)),
                ('ios3', models.CharField(default='', max_length=3)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('cases', models.IntegerField(default=0)),
                ('todayCases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('todayDeaths', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('casesPerOneMillion', models.IntegerField(default=0)),
                ('deathsPerOneMillion', models.IntegerField(default=0)),
                ('bearing', models.DecimalField(decimal_places=2, max_digits=4)),
                ('zoom', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
