# Generated by Django 3.0.4 on 2020-04-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200411_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='ios2',
            new_name='iso2',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='ios3',
            new_name='iso3',
        ),
    ]
