# Generated by Django 3.0.4 on 2020-04-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200411_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='flag',
            field=models.URLField(default=''),
        ),
    ]
