# Generated by Django 3.0.4 on 2020-04-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_countries_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='continent',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
