# Generated by Django 3.0.5 on 2020-04-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_countries_continent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
    ]
