# Generated by Django 3.0.5 on 2020-05-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200502_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='country',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='country',
            name='tests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
