# Generated by Django 3.0.5 on 2020-05-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200502_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['priority'], 'verbose_name': 'Country List', 'verbose_name_plural': 'Countries List'},
        ),
        migrations.AddField(
            model_name='country',
            name='testsPerOneMillion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['country'], name='country'),
        ),
    ]
